### ISSUE TITLE
expr: syntax error

### ISSUE THREAD

**Issue by MartinDelille** [oh-my-fish/theme-budspencer#57]
Each time I type a type a fish command I have the following error:

```
$ fish --version
fish, version 3.0.0-172-g6d11e464
expr: syntax error
[: Missing argument at index 2
```

**Comment by kinjoBobchin** [comment]
same error orz

**Comment by kinjoBobchin** [comment]
```
fish, version 3.0.2
expr: syntax error
[: Missing argument at index 2
```

**Comment by kinjoBobchin** [comment]
then, i tried to uninstall fish...

error message is here

```
Uninstalling /usr/local/Cellar/fish/3.0.2... (953 files, 8.3MB)
fish: Unknown command fish_indent
~/.config/fish/functions/fish_prompt.fish (line 1): 
echo $history[1] | fish_indent | expand -t 4
                   ^
in command substitution
	called on line 527 of file ~/.config/fish/functions/fish_prompt.fish

in function '__budspencer_create_cmd_hist'
	called on standard input

in event handler: handler for generic event 'fish_prompt'

set: You provided 1 indexes but 0 values
expr: syntax error
contains: Key not specified
expr: syntax error
[: Missing argument at index 2
```

syntax error ... orz

**Comment by clayauld** [comment]
Looks like you're using Homebrew on MacOS. I'm not getting that issue at all on my installation. Can you update your omf installation to see if a fix has been pushed already?

**Comment by anrock42** [comment]
For me I fixed it by setting the the locale settings in my `~/.config/fish/config.fish` like this:
`set -xU LC_ALL en_US.UTF-8`

**Comment by clayauld** [comment]
I noticed the error only occurs when the shell is running inside a git repo. I'm seeing the issue now.

**Comment by Shub1427** [comment]
This issue is not resolved, still getting an error message inside git repo @clayauld .
<img width="1387" alt="error-msg-budspencer" src="https://user-images.githubusercontent.com/11786283/68450096-c6206c00-020f-11ea-98af-b498d16bbdb7.png">

**Comment by clayauld** [comment]
What version of `expr` and `sed` are you using? There are known issues with the versions included in MacOS. If you do not have the versions installed from Homebrew try that. More info can be found in the Readme about this.

**Comment by MartinDelille** [comment]
I'm also still having the issue. I don't know how to get the version of `expr` and `sed` but I'm using the one from *MacOS Mojave*:

```
$ which expr
/bin/expr
$ which sed
/usr/bin/sed
```

**Comment by Shub1427** [comment]
Yeah @clayauld It got fixed, once I changed to GNU tools. For other's ref, do the following:

```
brew install coreutils gnu-sed
```

> Above command installs `g` prefixed commands for their MacOS alternates.

To fix that, add this to your `~/.config/fish/config.fish`:

```
if test (uname -s) = "Darwin"
  set -gx PATH /usr/local/opt/coreutils/libexec/gnubin $PATH
  set -gx PATH /usr/local/opt/gnu-sed/libexec/gnubin $PATH
end
```

**Comment by MartinDelille** [comment]
I followed your advice and now have the following:

```
$ which expr
/usr/local/opt/coreutils/libexec/gnubin/expr
$ which sed
/usr/local/opt/gnu-sed/libexec/gnubin/sed
```

Unfortunately, when installing `theme-budspencer`, I still have this error message:

```
$ ls
~/.config/fish/functions/fish_prompt.fish (line 681): switch: Expected exactly one argument, got 0

  switch $pwd_style
         ^
in function '__budspencer_prompt_bindmode'
	called on line 884 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 1768 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

~/.config/fish/functions/fish_prompt.fish (line 647): switch: Expected exactly one argument, got 0

    switch $pwd_style
           ^
in function '__budspencer_prompt_git_branch'
	called on line 884 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 1768 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

~/.config/fish/functions/fish_prompt.fish (line 807): switch: Expected exactly one argument, got 0

    switch $pwd_style
           ^
in function '__budspencer_prompt_left_symbols'
	called on line 884 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 1768 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

~/.config/fish/functions/fish_right_prompt.fish (line 143): switch: Expected exactly one argument, got 0

    switch $pwd_style
           ^
in function '__budspencer_prompt_git_symbols'
	called on line 266 of file ~/.config/fish/functions/fish_right_prompt.fish

in command substitution
	called on line 531 of file ~/.config/fish/functions/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input

~/.config/fish/functions/fish_right_prompt.fish (line 248): switch: Expected exactly one argument, got 0

    switch $pwd_style
           ^
in function '__budspencer_prompt_pwd'
	called on line 266 of file ~/.config/fish/functions/fish_right_prompt.fish

in command substitution
	called on line 531 of file ~/.config/fish/functions/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input
```

It seems to be related to #46

**Comment by clayauld** [comment]
after installing the theme please run ``exec fish``. According to #46 starting a new session fixed his issue.
